class TagGroupImport
  
  @@tag_group_mappings = Hash["Accountants Certified Public" => "Accounting and Bookkeeping Services",
                              "Advertising Aerial" => "Advertising",
                              "Advertising Agencies" => "Advertising",
                              "Advertising Direct Mail" => "Advertising",
                              "Advertising Directory and Guide" => "Advertising",
                              "Advertising Electronic and Fax" => "Advertising",
                              "Advertising Newspaper" => "Newspapers",
                              "Advertising Outdoor" => "Advertising",
                              "Advertising Promotional Products and Services" => "Advertising",
                              "Advertising Radio" => "Advertising",
                              "Advertising Specialties" => "Advertising",
                              "Aids Hiv Educational Referral and Support Services" => "Aids Resources", 
                              "Air Conditioning Contractors and Systems" => "Heating, Ventilation and Air Conditioning",
                              "Air Conditioning Equipment and Systems Repairing" => "Heating, Ventilation and Air Conditioning",
                              "Air Conditioning Supplies and Parts Wholesale" => "Heating, Ventilation and Air Conditioning",
                              "Air Conditioning Systems Cleaning" => "Heating, Ventilation and Air Conditioning",
                              "Air Cargo and Package Express Service" => "Cargo and Freight Services",
                              "Aircraft Charter Rental and Leasing" => "Aircraft Charters and Rentals",
                              "Aircraft Charters Rental and Leasing" => "Aircraft Charters and Rentals",
                              "Aircraft Dealers" => "Aircraft Dealers and Services",
                              "Aircraft Service and Maintenance" => "Aircraft Dealers and Services",
                              "Airline Companies" => "Airlines",
                              "Airport Transportation Service" => "Airport Transportation", 
                              "Alcoholism Information and Treatment Centers" => "Drug and Alcohol Resources",
                              "Alterations Clothing" => "Clothing Alterations",
                              "Ambulance Service" => "Ambulance and Rescue Services",
                              "Animal Shelters" => "Animal Shelters and Humane Societies",
                              "Antique Dealers" => "Antiques",
                              "Antique Restoration and Preservation" => "Antiques",
                              "Apartment Referral Service" => "Apartment Referrals",
                              "Appliance Supplies and Parts" => "Appliance Repair and Supplies",
                              "Appraisers" => "Real Estate - Appraisers",
                              "Architects and Builders Service" => "Architects",
                              "Architects Supplies" => "Architects",
                              "Art Galleries Dealers and Consultants" => "Artists and Art Dealers",
                              "Artists Commercial" => "Artists",
                              "Artists Fine Art" => "Artists",
                              "Arts Organizations and Centers" => "Art Centers and Organizations",
                              "Asphalt and Asphalt Products" => "Contractors - Paving",
                              "Assisted Living Facilities" => "Retirement and Assisted Living Facilities",
                              "Attorneys Accident Personal Injury and Property Damage Law" => "Law - Personal Injury and Property Damage",
                              "Attorneys Administrative and Government Law" => "Law - Governmental Issues",
                              "Attorneys Adoption Law" => "Attorneys",
                              "Attorneys Appellate Practice" => "Attorneys",
                              "Attorneys Bankruptcy Law" => "Law - Financial and Bankruptcy",
                              "Attorneys Business Corporation and Partnership Law" => "Law - Business and Corporate",
                              "Attorneys Civil Trial Law" => "Law - Civil",
                              "Attorneys Collections Law" => "Law - Financial and Bankruptcy",
                              "Attorneys Construction Law" => "Attorneys",
                              "Attorneys Consumer Rights Law" => "Attorneys",
                              "Attorneys Criminal Law" => "Law - Criminal",
                              "Attorneys Driving Dui Dwi Law" => "Law - Driving and Traffic",
                              "Attorneys Elder Law" => "Attorneys",
                              "Attorneys Employment and Labor Law" => "Law - Labor and Employment",
                              "Attorneys Immigration and Naturalization Law" => "Law - Immigration and Naturalization",
                              "Attorneys Juvenile Law" => "Law - Juvenile",
                              "Attorneys Malpractice Law" => "Law - Malpractice",
                              "Attorneys Marriage and Family Law" => "Law - Divorce and Family",
                              "Attorneys Patent Law" => "Law - Patent, Trademark and Copyright",
                              "Attorneys Real Estate Law" => "Law - Real Estate",
                              "Attorneys Tax Law" => "Law - Taxes",
                              "Attorneys Trademark and Copyright Law" => "Law - Patent, Trademark and Copyright",
                              "Attorneys Traffic and Vehicle Law" => "Law - Driving and Traffic",
                              "Attorneys Wills Trusts and Estate Planning Law" => "Law - Wills and Estate Planning",
                              "Audio Visual Equipment Dealers" => "Electronics - Audio Visual",
                              "Audio Visual Equipment Wholesale and Manufacturers" => "Electronics - Audio Visual",
                              "Automation Systems and Equipment" => "Automation and Control Systems",
                              # "Automobile STUFF"
                              "Automobile Accessories and Trim" => "Automobile - Parts and Accessories",
                              "Automobile Air Conditioning Equipment and Supplies" => "",
                              "Automobile Alarms and Security Systems" => "Automobile - Alarms and Security",
                              "Automobile Body Repairs and Painting" => "Automobile - Body Repairs and Painting",
                              "Automobile Body Shop Equipment and Supplies" => "Automobile - Body Repairs and Painting",
                              "Automobile Body Shop Services" => "Automobile - Body Repairs and Painting",
                              # "Automobile Customizing" => "",
                              "Automobile Dealers Antique and Classic" => "Automobile - Dealers",
                              "Automobile Dealers New and Used" => "Automobile - Dealers",
                              "Automobile Dealers Used Cars and Vans" => "Automobile - Dealers",
                              "Automobile Dealers Used Cars Wholesale" => "Automobile - Dealers",
                              "Automobile Dealers" => "Automobile - Dealers",
                              "Automobile Detailing and Clean Up Service" => "Automobile - Wash and Detailing",
                              "Automobile License and Title Services" => "Automobile - License and Title Services",
                              "Automobile Leasing" => "Automobile - Leasing",
                              "Automobile Oil and Lubrication Services" => "Automobile - Oil and Lubrication",
                              "Automobile Parts and Accessories" => "Automobile - Parts and Accessories",
                              "Automobile Parts and Supplies" => "Automobile - Parts and Accessories",
                              "Automobile Parts and Supplies Antique and Classic" => "Automobile - Parts and Accessories",
                              "Automobile Parts and Supplies Used and Rebuilt" => "Automobile - Parts and Accessories",
                              "Automobile Parts and Supplies Wholesale and Manufacturers" => "Automobile - Parts and Accessories",
                              "Automobile Rentals" => "Automobile - Rentals",
                              "Automobile Renting and Leasing" => "Automobile - Rentals",
                              "Automobile Repair and Service Equipment and Supplies" => "Automobile - Repairs and Services",
                              "Automobile Repairs and Services" => "Automobile - Repairs and Services",
                              "Automobile Repair and Service Equipment and Supplies" => "Automobile - Repairs and Services",
                              "Automobile Restoration Antique and Classic" => "Automobile - Repairs and Services",
                              "Automobile Tires" => "Automobile - Tires",
                              "Automobile Towing" => "Automobile - Towing",
                              "Automobile Wash and Detailing" => "Automobile - Wash and Detailing",
                              "Bagels" => "Bagels",
                              "Bakers" => "Bakers",
                              "Bakers Wholesale" => "Bakers",
                              "Bakery Equipment" => "Bakery Equipment and Supplies",
                              "Bakery Supplies" => "Bakery Equipment and Supplies",
                              "Banks" => "Banks and Credit Unions",
                              "Banks and Credit Unions" => "Banks and Credit Unions",
                              "Banks Commercial" => "Banks and Credit Unions",
                              "Barber" => "Barber",
                              "Bars Grills and Pubs" => "Bars, Grills and Pubs",
                              "Batteries Retail" => "Electronics - Batteries",
                              "Beauty Salons" => "Beauty Salons and Day Spas",
                              "Beauty Salon Equipment and Supplies Wholesale and Manufacturers" => "Hair and Beauty Supplies, Service and Equipment",
                              "Beauty Skin Care" => "Beauty Skin Care",
                              "Beauty Supplies and Equipment" => "Hair and Beauty Supplies, Service and Equipment",
                              "Beer and Ale Retail" => "Beer and Ale Retail",
                              "Beer and Ale Wholesale" => "Beer and Ale Wholesale",
                              # Building ...
                              # "Cafes" => "Cafes",
                              "Child Care Services" => "Child Care Centers and Services",
                              # Cleaners
                              # Clinics Medical
                              # Clothing ...
                              # Coffee and Tea Retail
                              # Coffee and Tea Wholesale
                              "Clothing" => "Clothing and Accessories",
                              "Clothing Vintage" => "Clothing Vintage",
                              "Clothing Vintage and Collectible" => "Clothing Vintage",
                              "Consultants Business" => "Consultants - Business",
                              "Consultants Environment" => "Consultants - Environment",
                              # Contractors General
                              "Contractors Building" => "Contractors - Building",
                              "Contractors Carpentry" => "Contractors - Carpentry",
                              "Contractors Computer" => "Contractors - Computer",
                              "Contractors Concrete" => "Contractors - Concrete",
                              "Contractors Drywall" => "Contractors - Drywall",
                              "Contractors Electric" => "Contractors - Electrical",
                              "Contractors Electrical" => "Contractors - Electrical",
                              "Contractors Excavation and Wrecking" => "Contractors - Excavation and Wrecking",
                              "Contractors Insulation" => "Contractors - Insulation",
                              "Contractors Masonry" => "Contractors - Masonry",
                              "Contractors Painting" => "Contractors - Painting",
                              "Contractors Paving" => "Contractors - Paving",
                              "Contractors Plumbers and Plumbing" => "Contractors - Plumbers and Plumbing",
                              "Contractors Roofing" => "Contractors - Roofing",
                              "Contractors Sewer" => "Contractors - Sewer",
                              "Contractors Siding" => "Contractors - Siding",
                              "Contractors Tile, Marble and Granite" => "Contractors - Tile, Marble and Granite",
                              "Convenience Stores" => "Convenience Stores and Service Stations",
                              "Credit Unions" => "Banks and Credit Unions",
                              "Currency Exchanges" => "Currency Exchange",
                              "Electronics Audio Visual" => "Electronics - Audio Visual",
                              "Electronics Computers" => "Electronics - Computers",
                              "Electronics Dealers" => "Electronics - Dealers",
                              "Electronics Equipment and Services" => "Electronics - Equipment and Services",
                              "Electronics Home Entertainment" => "Electronics - Home Entertainment",
                              "Electronics Printers" => "Electronics - Printers",
                              "Electronics Telephone" => "Electronics - Telephone",
                              "Engineers Civil" => "Engineers - Civil",
                              "Engineers Electrical" => "Engineers - Electrical",
                              "Engineers Environmental" => "Engineers - Environmental",
                              "Engineers Forensic" => "Engineers - Forensic",
                              "Engineers Geotechnical Soils" => "Engineers - Geotechnical Soils",
                              "Engineers Mechanical" => "Engineers - Mechanical",
                              "Engineers Professional" => "Engineers - Professional",
                              "Engineers Structural" => "Engineers - Structural",
                              "Fashion Designers" => "Fashion Design",
                              "Financial Services" => "Financial Services",
                              "Hardware" => "Hardware Tools and Services",
                              "Liquor Stores Retail" => "Liquor Stores",
                              "Loans" => "Loans and Mortgages",
                              "Modeling" => "Modeling",
                              "Modeling Agencies" => "Modeling Agencies",
                              "Mortgages" => "Loans and Mortgages",
                              # "Museums" => "",
                              "Optometrists Od" => "Physicians - Optometry and Opthalmology",
                              "Physicians and Surgeons" => "Physicians - General",
                              "Physicians and Surgeons Allergy Asthma and Immunology" => "Physicians - Allergy Asthma and Immunology",
                              "Physicians and Surgeons Anesthesiology" => "Physicians - Anesthesiology",
                              "Physicians and Surgeons Cardiology" => "Physicians - Cardiology",
                              "Physicians and Surgeons Dpm Podiatrists" => "Physicians - Podiatry",
                              "Physicians and Surgeons Family and General Practice" => "Physicians - Family and General Practice",
                              "Physicians and Surgeons Internal Medicine" => "Physicians - Internal Medicine",
                              "Physicians and Surgeons Neurology" => "Physicians - Neurology and Neurosurgery",
                              "Physicians and Surgeons Obstetrics and Gynecology" => "Physicians - Obstetrics and Gynecology",
                              "Physicians and Surgeons Opthalmology" => "Physicians - Optometry and Opthalmology",
                              "Physicians and Surgeons Pediatrics" => "Physicians - Pediatrics",
                              "Physicians and Surgeons Psychiatry" => "Physicians - Psychiatry",
                              "Physicians and Surgeons Radiology" => "Physicians - Radiology",
                              "Physicians and Surgeons Surgery General" => "Physicians - General",
                              "Physicians and Surgeons Surgery Hand" => "Physicians - Hand",
                              "Physicians Naturopathic Nmd" => "Physicians - Alternative",
                              "Railroad Construction" => "Railroads",
                              # "Real Estate" => "",
                              "Real Estate Apartments and Condominiums" => "Real Estate - Apartments and Condominiums",
                              "Real Estate Appraisers" => "Real Estate - Appraisers",
                              "Real Estate Brokers and Agents" => "Real Estate - Brokers and Agents",
                              "Real Estate Commercial and Industrial" => "Real Estate - Commercial and Industrial",
                              "Real Estate Consultants" => "Real Estate - Consultants",
                              "Real Estate Developers" => "Real Estate - Development",
                              "Real Estate Development" => "Real Estate - Development",
                              "Real Estate Investments" => "Real Estate - Investments",
                              "Real Estate Property Management" => "Real Estate - Property Management",
                              "Real Estate Rental Service" => "Real Estate - Rental Service",
                              "Real Estate Schools and Courses" => "Real Estate - Schools and Courses",
                              "Real Estate Title Companies" => "Real Estate - Title Companies",
                              "Restaurants Delicatessens" => "Restaurants Delicatessen",
                              "Restaurants Dining" => "Restaurants",
                              "Restaurants Take Out" => "Restaurants Carry Out Foods",
                              # "Restaurants Barbecue" => "Restaurants - Barbecue",
                              # "Restaurants Cafeterias" => "Restaurants - Cafeterias",
                              # "Restaurants Chinese" => "Restaurants - Chinese",
                              # "Restaurants Delivery Service and Take Out" => "Restaurants - Delivery Service and Take Out",
                              # "Restaurants Cafeterias" => "",
                              # "Restaurants Chinese" => "",
                              # "Restaurants Delivery Service and Take Out" => "",
                              # "Restaurants Fast Food" => "",
                              # "Restaurants Mexican" => "Restaurants - Mexican",
                              # "Restaurants Pizza" => "Restaurants - Pizza",
                              # "Restaurants Seafood" => "Restaurants - Seafood",
                              "Schools Private" => "Schools - Private",
                              "Schools Religious Education" => "Schools - Religious",
                              "Tax Return Preparation and Filing" => "Tax Preparation",
                              "Vintage Clothing Stores" => "Clothing Vintage"
                             ]
                             
  
  def self.normalize(s)
    s.split.map do |s|
      case
      when ['and', '&'].include?(s.downcase)
        'and'
      when s == '-'
        '-'
      else
        s.strip.titleize
      end
    end.join(" ")
  end
  
  def self.to_tag_group(s)
    s  = normalize(s)
    tg = TagGroup.find_all_by_name(s)
    return tg if !tg.empty?

    # map string to a tag group name
    s_mapped = @@tag_group_mappings[s]
    
    TagGroup.find_all_by_name(s_mapped)
  end
end